### PR TITLE
imp: get client version from .env file

### PR DESCRIPTION
**Pull request by s4kh**
See #4. Used https://github.com/joho/godotenv for loading env var.

### CODE REVIEW

**Comment by s4kh** [comment]
Currently, the build gives an error about clientVersion is not being used. Where do we use that? @k1m0ch1

**Comment by s4kh** [comment]
> Currently, the build gives an error about clientVersion is not being used. Where do we use that? @k1m0ch1

The last commit addressesd this.

**Comment by k1m0ch1** [comment]
@s4kh you need to add the `.env.example` for example of the `.env` file

**Comment by k1m0ch1** [comment]
LGTM

**Pull request merged**
